version: "3.8"

services:
  chat:
    build: .
    container_name: fastapi-chat
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
